language: node_js
node_js: '10'
sudo: false
cache: yarn
stages:
- test
- deploy
- compile
- build
install:
- yarn global add lerna
- yarn --silent --non-interactive --ignore-scripts
jobs:
  include:
  - script: commitlint-travis
  - before_install: yarn global add greenkeeper-lockfile@1
    before_script: greenkeeper-lockfile-update
    script: yarn prepare
    after_script: greenkeeper-lockfile-upload
  - script:
    - yarn prepare:fscodestyle
    - yarn lint
  - script: yarn test --coverage --ci && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - script:
    - yarn prepare
    - yarn build:storybook
  - language: android
    android:
      components:
      - build-tools-26.0.2
      - build-tools-25.0.3
      - build-tools-23.0.1
      - android-26
      - android-23
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-26
      - addon-google_apis-google-23
    before_install:
    - nvm install 10
    # The default Android image has an old version of Yarn that doesn't support workspaces
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
    - export PATH=$HOME/.yarn/bin:$PATH
    - node --version
    - yarn --version
    script:
    - yarn prepare
    - yarn ship:init
    - yarn ship:compile-android
  - stage: compile
    if: type = pull_request
    language: objective-c
    os: osx
    osx_image: xcode9.4
    before_install:
    - nvm install 10
    - brew install yarn --without-node
    - node --version
    - yarn --version
    script:
    - yarn prepare
    - yarn ship:init
    - yarn ship:compile-ios
  - stage: build
    if: type = push
    language: objective-c
    os: osx
    osx_image: xcode9.4
    env:
    - KEY_CHAIN=ios-build.keychain
    before_install:
    - nvm install 10
    - brew install yarn --without-node
    - node --version
    - yarn --version
    script:
    - yarn prepare
    - yarn ship:init
    - yarn ship:build-ios
  - stage: deploy
    if: branch = master AND head_branch IS blank
    before_install: npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN} -q
    script:
    - yarn prepare
    - yarn docs
    after_success: yarn run release --canary --yes --exact
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      local-dir: docs/
      on:
        branch: master
